### ISSUE TITLE
interference when using `fish_config`

### ISSUE THREAD

**Issue by gretel** [fish-shell/wahoo#39]
with wahoo installed i did call `fish_config` to check if the web interface is still there :)
it is, but when i changed prompt using it i couldnt get back to the one implied by the theme while not having any obvious persistency

**Comment by bucaran** [comment]
Indeed you can't. This must have to do with the way themes work in Wahoo.

**Comment by gretel** [comment]
i see. could be possible buggy upstream then, you on the `fish` project, too?

**Comment by bucaran** [comment]
Not a collaborator, but can give it a shot after I check things on our side.

**Comment by bucaran** [comment]
Can we close this? `fish_config` is working for me.

**Comment by joefiorini** [comment]
I'm trying to understand this issue. I just installed fish today, created a custom prompt, then changed it via `fish_config` to try to troubleshoot why the git settings weren't working for me. Now I can see no way to get the prompt back to my custom one in my wahoo theme. Is this impossible?

**Comment by bucaran** [comment]
Hi @joefiorini 

I typed `fish_config` and got a little screen like this:

<img width="1034" alt="screen shot 2015-07-30 at 3 55 43 am" src="https://cloud.githubusercontent.com/assets/8317250/8966900/e2b2e40e-366e-11e5-81dc-0dd29d38c522.png">

I then selected the `Solarized Light`, switched back to the terminal and pressed ENTER to stop the SocketServer.

Obviously the background of the terminal did not change, because for that you need to customize your Terminal.app, iTerm.app, etc., but the colors fish uses when you type and when you get auto completion did change accordingly.

**Comment by joefiorini** [comment]
Correct. I'm talking about the prompt setting though. Either way, I seem to have fixed it by changing my `WAHOO_CUSTOM` variable to `~/.wahoo` instead of `~/.dotfiles`. That seems like a weird default, no?

**Comment by bucaran** [comment]
Also, post your Wahoo theme to help you debug the issue.

**Comment by bucaran** [comment]
`$WAHOO_CUSTOM` should be `~/.dotfiles` or whatever you choose for dotfiles, mine is `~/.rc`. How could it be `~/.wahoo`, that is `$WAHOO_PATH`. This is terifying :disappointed_relieved:

**Comment by bucaran** [comment]
See here

```fish
local WAHOO_CONFIG="${HOME}/.config/wahoo"
test -z ${CUSTOM+_} && CUSTOM="${BASE}/.dotfiles"
```

**Comment by joefiorini** [comment]
@bucaran I installed it following the instructions in the `README`, so `curl -L git.io/wa | sh`. FWIW, I'm running fish 2.2.0 on Arch.

I'm realzing that changing `WAHOO_CUSTOM` didn't actually help anything. It just causes new Terminal sessions to hang until I Ctrl+C, then I get my custom prompt, probably because it never had a chance to load the `fish_config` prompt I chose. If I change it back to `.dotfiles` (which doesn't exist), the Terminal session loads just fine, but gives me the prompt I picked in `fish_config` rather than my custom one.

All I want to figure out is how I get my custom prompt using my Wahoo theme rather than the one I chose in `fish_config`. Is this possible?

**Comment by bucaran** [comment]
@joefiorini I can help you debug this, but you need to help me a bit.

What is a custom prompt? Do you mean you have a file somewhere with a `fish_prompt` function, like:

```fish
function fish_prompt
...
end
```

**Comment by joefiorini** [comment]
@bucaran Okay, newb moment. For the sake of anyone else running into this issue: It appears `fish_config` writes the selected prompt to `~/.config/fish/functions/fish_prompt.fish`. That prompt takes precedence over the one specified by the wahoo theme. So remove that directory and it should be all better.

**Comment by bucaran** [comment]
@joefiorini Oh, I get it now... Yes, you are correct. This information must go into the README or the FAQ somewhere for sure. Or maybe Wahoo can offer some help. How could have Wahoo helped you fix this problem faster?

**Comment by joefiorini** [comment]
@bucaran Perhaps a message on startup that says "We see you have activated a theme and have a fish prompt under `~/.config/fish/functions/fish_prompt.fish`. Remove that file if you want to use your theme's prompt" or something along those lines?

Another option might be having the `fish_config` web interface tell you where it persisted the file after you set a prompt. That would keep Wahoo from being annoying if the `fish_config` prompt is actually what you want.

I think a README or FAQ update would make sense for the time being though. Happy to send a PR for that.

**Comment by bucaran** [comment]
@joefiorini Thanks. So clearly, fish_config themes are not compatible with Wahoo, but if the only part that gets replaced is `fish_prompt` what happens to the other theme functions like say `fish_right_prompt`? I suspect, that would depend on the theme itself...

I think Wahoo could do more for us here. For example, not autoloading any theme at all if a theme file exists under `~/.config/fish/functions/` like `fish_prompt.fish` or `fight_right_prompt.fish`, etc. as well as displaying a message if you try to switch themes.

In addition an option to remove that fish theme file under `functions/` could be added as well.
